Split Travis CI linux build in two separate builds

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,9 +1,29 @@
 sudo: false
 language: cpp
 
-os:
-  - linux
-  - osx
+git:
+  depth: 1
+
+matrix:
+  include:
+  - os: linux
+    compiler: g++-4.7
+    env: COMPILER=g++-4.7
+    cache:
+      directories:
+      - $HOME/SFML_LINUX
+
+  - os: linux
+    compiler: g++-5
+    env: COMPILER=g++-5
+    cache:
+      directories:
+      - $HOME/SFML-2.2_LINUX
+
+  - os: osx
+    cache:
+      directories:
+      - $HOME/SFML_OSX
 
 addons:
   apt:
@@ -12,28 +32,43 @@ addons:
     packages:
     - g++-4.7
     - g++-5
-    - libpthread-stubs0-dev
-    - libgl1-mesa-dev
+
+    - libfreetype6-dev
+    - libjpeg-dev
     - libx11-dev
     - libxrandr-dev
-    - libfreetype6-dev
+    - libxcb1-dev
+    - libx11-xcb-dev
+    - libxcb-randr0-dev
+    - libxcb-image0-dev
+    - libgl1-mesa-dev
+    - libflac-dev
+    - libogg-dev
+    - libvorbis-dev
+    - libvorbisenc2
+    - libvorbisfile3
+    - libopenal-dev
+    - libpthread-stubs0-dev
+
     - libglew-dev
-    - libjpeg-dev
     - libgpgme11-dev
     - libsndfile1-dev
-    - libopenal-dev
     - libudev-dev
-
-cache:
-  directories:
-  - $HOME/SFML_LINUX
-  - $HOME/SFML_OSX
 
 script:
   - >
+    CXX=$COMPILER;
     if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
-      chmod +x tests/travis_linux.sh
-      tests/travis_linux.sh
+      if [[ $CXX == g++-4.7 ]]; then
+        chmod +x tests/travis_linux.sh
+        tests/travis_linux.sh
+      elif [[ $CXX == g++-5 ]]; then
+        chmod +x tests/travis_linux_tests.sh
+        tests/travis_linux_tests.sh
+      else
+        echo 'Invalid compiler'
+        exit 1
+      fi
     elif [[ $TRAVIS_OS_NAME == 'osx' ]]; then
       chmod +x tests/travis_osx.sh
       tests/travis_osx.sh
@@ -44,6 +79,6 @@ script:
 
 after_success:
   - >
-    if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
+    if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == g++-5 ]]; then
       bash <(curl -s https://codecov.io/bash) -x gcov-5 -a "-s /home/travis/build/texus/TGUI -pr"
     fi
